# WARNING: Passwords are currently only set for the initial setup. If you want to change
#          your passwords later, you will have to do so manually.

# NOTE:    The passwords listed by default in this file are meant as an example,
#          please replace!

[general]
    libertas_root = "/home/user/libertas" # NO TRAILING SLASHES!
    domain = "mydomain.com"

[database]
    [database.passwords]
    root = "CnCQPKA6tQLTuY8WcV4UCT6m"
    user = "Z9zrNsKMVYTxXg7VqZjLqy7d"

[dockermail]
    [dockermail.server]
        [dockermail.server.passwords]
            mysql_user = "QzkLdTQs6E948nNc6CLTuuySq57Y"

    [dockermail.client]
        [dockermail.client.users]
            [dockermail.client.user.myuser]
                password = "some!convenient@$but*long^password*with&a)bit3of6randomness"

[traefik]
    acme_email = "user@mydomain.com"

[matrix]
    domain = "matrix.mydomain.com"