version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik2"
    command:
      #- "--log.level=DEBUG"
#      - "--api.insecure=false"
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.mytlschallenge.acme.email=
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      - --providers.file.directory=/dynamic_config
      - --providers.file.watch=true
    ports:
      - "443:443"
#      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic_config:/dynamic_config:ro"
    networks:
      - frontend
      - default
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file

networks:
  frontend:
    external:
      name: frontend
  default:
    driver: bridge
